// One-bit full adder.
//
// Adds a, b, and carryin. The two-bit arithmetic result is represented by
// {carryout, result}:
//   result   = a XOR b XOR carryin
//   carryout = (a AND b) OR (carryin AND (a XOR b))
module oneadder (
    input a,
    input b,
    input carryin,
    output result,
    output carryout
);
    wire wire1; // a XOR b
    wire wire2; // carry generated by a and b
    wire wire3; // carry generated by carryin

    // Sum path.
    xor xor1(wire1, a, b);
    xor xor2(result, wire1, carryin);

    // Carry path.
    and and1(wire2, a, b);
    and and2(wire3, wire1, carryin);
    or or1(carryout, wire2, wire3);
endmodule
